### ISSUE TITLE
This incredibly helpful tool stopped working :(

### ISSUE THREAD

**Issue by Shibenik** [Bitim/hebrew-tooltip-translations-webextension#1]
My browser is Firefox. When hovering over a word, the usual gray square with a turning wheel inside appears but after about 3 seconds disappears without the translation. This happened at the same time on both my PC and the laptop, which tells me that the problem is not in my devices. I uninstalled and reinstalled the add-on but no success. Googled "hebrew tooltip translation not working" and "hebrew tooltip translation stopped working" but there seem to be no discussions of this kind online. Please help. Thank you!

**Comment by yaadm** [comment]
Ok Shibenik, i forked and fixed the issue.
for now, the fixed version is here:
https://github.com/yaadm/hebrew-tooltip-translations-webextension

If the owner can just commit this changes to the Firefox store it could be nice. :)

**Comment by sha-265** [comment]
Thanks @yaadm, I pulled request your fix (and made other fix), and the fixed version is available on [Firefox's AMO site](https://addons.mozilla.org/en-US/firefox/addon/hebrew-tooltip-translation/) (or just update from FF's addon manager).

Thanks again.

**Comment by yaadm** [comment]
Good Job, i will delete the copy i made.
כל הכבוד אחי

**Comment by Shibenik** [comment]
Thank you very much for fixing the tool. And again a huge thank-you for
creating it!
